import os
from PIL import Image

C64_PALETTE = [
    (0, 0, 0),       # Black
    (255, 255, 255), # White
    (136, 0, 0),     # Red
    (170, 255, 238), # Cyan
    (204, 68, 204),  # Purple
    (0, 204, 85),    # Green
    (0, 0, 170),     # Blue
    (238, 238, 119), # Yellow
    (221, 136, 85),  # Orange
    (102, 68, 0),    # Brown
    (255, 119, 119), # Light Red
    (51, 51, 51),    # Dark Grey
    (119, 119, 119), # Grey
    (170, 255, 102), # Light Green
    (0, 136, 255),   # Light Blue
    (187, 187, 187)  # Light Grey
]

def closest_color(r, g, b):
    min_dist = float('inf')
    best_color = C64_PALETTE[0]
    for (cr, cg, cb) in C64_PALETTE:
        dist = (r - cr)**2 + (g - cg)**2 + (b - cb)**2
        if dist < min_dist:
            min_dist = dist
            best_color = (cr, cg, cb)
    return best_color

def process():
    in_path = r"C:\Users\mirko\.gemini\antigravity\brain\4559d6bc-f83b-4965-9736-4d602bce6032\creepy_stairs_base_1771972901207.png"
    out_path = r"C:\Users\mirko\Downloads\workspace\c64-dungeon\creepy_stairs_c64.png"
    
    img = Image.open(in_path).convert("RGB")
    
    # Crop the top 15% to remove any text generated by the AI
    width, height = img.size
    crop_height = int(height * 0.15)
    img = img.crop((0, crop_height, width, height))
    
    data = img.getdata()
    
    new_data = [closest_color(r, g, b) for r, g, b in data]
    img.putdata(new_data)
    
    # Scale it down and up for chunky pixels
    width, height = img.size
    small = img.resize((width // 4, height // 4), Image.NEAREST)
    final = small.resize((width, height), Image.NEAREST)
    
    final.save(out_path)
    print("Done processing image.")

process()
